- id: "99120100248"
  path: /resources/sounds/bgm/battleBGM.ogg
  _comment: Music
- id: "99120100249"
  path: /resources/sounds/bgm/bgm.ogg
  _comment: Music
- id: "99120100250"
  path: /resources/sounds/bgm/Story_01.ogg
  _comment: Music
- id: "99120100251"
  path: /resources/sounds/bgm/Battle_07.ogg
  _comment: Music
- id: "99120100252"
  path: /resources/sounds/bgm/Battle_08.ogg
  _comment: Music
- id: "99120100253"
  path: /resources/sounds/bgm/Battle_03.ogg
  _comment: Music
- id: "99120100254"
  path: /resources/sounds/bgm/mainBgm.ogg
  _comment: Music
- id: "99120110001"
  path: /resources/sounds/bgm/Story_02.ogg
  _comment: Music
- id: "99120110002"
  path: /resources/sounds/bgm/Story_04.ogg
  _comment: Music
- id: "99120110003"
  path: /resources/sounds/bgm/Story_06.ogg
  _comment: Music
- id: "99120110004"
  path: /resources/sounds/bgm/Story_07.ogg
  _comment: Music
- id: "99120110005"
  path: /resources/sounds/bgm/Story_08.ogg
  _comment: Music
- id: "99120110006"
  path: /resources/sounds/bgm/Story_09.ogg
  _comment: Music
- id: "99120110007"
  path: /resources/sounds/bgm/Battle_01.ogg
  _comment: Music
- id: "99120110008"
  path: /resources/sounds/bgm/Battle_02.ogg
  _comment: Music
- id: "99120110009"
  path: /resources/sounds/bgm/Battle_04.ogg
  _comment: Music
- id: "99120110010"
  path: /resources/sounds/bgm/Battle_05.ogg
  _comment: Music
- id: "99120110011"
  path: /resources/sounds/bgm/Battle_06.ogg
  _comment: Music
- id: "99120110012"
  path: /resources/sounds/bgm/UI_Main.ogg
  _comment: Music
- id: "99120110013"
  path: /resources/sounds/bgm/UI_PlayMode_Abnormal.ogg
  _comment: Music
- id: "99120110014"
  path: /resources/sounds/bgm/UI_PlayMode_Maze.ogg
  _comment: Music
- id: "99120110015"
  path: /resources/sounds/bgm/UI_PlayMode_Normal.ogg
  _comment: Music
- id: "99120110016"
  path: /resources/sounds/bgm/UI_ShopDraw.ogg
  _comment: Music
- id: "99120110017"
  path: /resources/sounds/bgm/Story_03.ogg
  _comment: Music
- id: "99120110018"
  path: /resources/sounds/bgm/Story_05.ogg
  _comment: Music
- id: "99120110019"
  path: /resources/sounds/bgm/UI_Main_Funk.ogg
  _comment: Music
- id: "99120110020"
  path: /resources/sounds/bgm/UI_Draw.ogg
  _comment: Music
- id: "99120110021"
  path: /resources/sounds/bgm/login.ogg
  _comment: Music
- id: "99120100530"
  path: /resources/sounds/bgm/Story_01.ogg
  _comment: Music
- id: "99120100531"
  path: /resources/sounds/bgm/EverythingisgonabeOK.ogg
  _comment: Music
- id: "99120100532"
  path: /resources/sounds/bgm/WW_BGM_01.ogg
  _comment: Music
- id: "99120100533"
  path: /resources/sounds/bgm/WW_BGM_02.ogg
  _comment: Music
- id: "99120100534"
  path: /resources/sounds/bgm/WW_BGM_03.ogg
  _comment: Music
- id: "99120100535"
  path: /resources/sounds/bgm/WW_BGM_04.ogg
  _comment: Music
- id: "99120100536"
  path: /resources/sounds/bgm/WW_BGM_05.ogg
  _comment: Music
- id: "99120100537"
  path: /resources/sounds/bgm/WW_BGM_06.ogg
  _comment: Music
- id: "99120100645"
  path: /resources/sounds/bgm/Story_15.ogg
  _comment: Music
- id: "99120100646"
  path: /resources/sounds/bgm/Story_16.ogg
  _comment: Music
- id: "99120100654"
  path: /resources/sounds/bgm/Story_17.ogg
  _comment: Music
- id: "99120100655"
  path: /resources/sounds/bgm/War_Drum.ogg
  _comment: Music
- id: "99120100692"
  path: /resources/sounds/bgm/WW_BGM_04p2.ogg
  _comment: Music
